Revert "SimSettings: Handle NoClassDefFoundError on devices without telephony-ext"
This reverts commit 0dfac363b5807104ec0a0a8f38d6d3617d3fd814.

i do a wrong cherry-pick i will fix later